using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CryptoCurrencyExchange.Data.Migrations
{
    public partial class MyFirstMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Rates",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AED = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AFN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ALL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AMD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ANG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AOA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AWG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AZN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BAM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BBD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BDT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BGN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BHD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BIF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BMD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BOB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BRL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BSD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BTN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BWP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BYN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BYR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BZD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CAD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CDF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CHF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CLF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CLP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CNY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    COP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CUC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CVE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CZK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DJF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DKK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DOP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DZD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EGP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ETB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EUR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FJD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FKP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GBP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GEL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GHS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GIP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GMD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GNF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GTQ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GYD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HKD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HNL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HRK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HTG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HUF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IDR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ILS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    INR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IQD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ISK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JMD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JOD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JPY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KES = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KGS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KHR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KMF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KRW = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KWD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KYD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KZT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LAK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LBP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LKR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LRD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LSL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LYD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MAD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MDL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MGA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MKD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MMK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MOP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MUR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MVR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MWK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MXN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MYR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MZN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NAD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NGN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NIO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NOK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NPR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NZD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OMR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PAB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PEN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PGK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PHP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PKR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PLN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PYG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    QAR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RON = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RSD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RUB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RWF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SAR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SBD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SCR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SEK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SHP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SLL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SOS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SRD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SSP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    STD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SVC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SZL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    THB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TJS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TOP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TRY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TTD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TWD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TZS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UAH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UGX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UYU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UZS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    VES = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    VND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    VUV = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XAF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XAG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XAU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XDR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XOF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XPD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XPF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XPT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XTS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    YER = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZAR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZMW = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JEP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GGP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IMP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GBX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CNH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LTL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZWD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZWL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    VEF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AUD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    USD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BTC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BCH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BSV = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ETH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ETH2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ETC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LTC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZRX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    USDC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BAT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LOOM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MANA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KNC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LINK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MKR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CVC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OMG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DAI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZEC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XRP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    REP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XLM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EOS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XTZ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ALGO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DASH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ATOM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OXT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    COMP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ENJ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    REPV2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BAND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NMR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CGLD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UMA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    YFI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UNI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BAL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    REN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WBTC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    YFII = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FIL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAVE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GRT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SNX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    STORJ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SUSHI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MATIC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SKL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ADA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ANKR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CRV = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ICP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NKN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OGN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    _1INCH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    USDT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FORTH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CTSI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TRB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    POLY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MIR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RLC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DOT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SOL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DOGE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MLN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GTC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AMP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SHIB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CHZ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KEEP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LPT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    QNT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BOND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RLY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CLV = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FARM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MASK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FET = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PAX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ACH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ASM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PLA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RAI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TRIBE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ORN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IOTX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    QUICK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AXS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    REQ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WLUNA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TRU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RAD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    COTI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DDX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SUKU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RGT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XYO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZEN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AUCTION = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BUSD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JASMY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WCFG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BTRST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AGLD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AVAX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TRAC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LCX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARPA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BADGER = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KRL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PERP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RARI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DESO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    API3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NCT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SHPING = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UPI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CRO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MTL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ABT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AVT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MDT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    VGX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ALCX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    COVAL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FOX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MUSD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CELR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GALA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    POWR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GYEN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ALICE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    INV = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LQTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PRO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SPELL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ENS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DIA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BLZ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CTX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ERN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IDEX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MCO2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    POLS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SUPER = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UNFI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    STX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KSM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GODS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IMX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RBN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BICO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GFI = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ATA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GLM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MPL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PLU = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWFTC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SAND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GNO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FIDA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ORCA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CRPT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    QSP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RNDR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NEST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PRQ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HOPR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JUP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MATH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SYN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AIOZ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WAMPL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AERGO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    INDEX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TONE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HIGH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GUSD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FLOW = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ROSE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    APE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MINA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MUSE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SYLO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DREP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ELA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FORT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ALEPH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DEXT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FIS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BIT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GST = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MEDIA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    C98 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BOBA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DAR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DYP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GAL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LOKA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    METIS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MONA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    POND = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RARE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    STG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TIME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XCN = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rates", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ExchangeRates",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Currency = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RatesId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExchangeRates", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ExchangeRates_Rates_RatesId",
                        column: x => x.RatesId,
                        principalTable: "Rates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ExchangeRates_RatesId",
                table: "ExchangeRates",
                column: "RatesId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ExchangeRates");

            migrationBuilder.DropTable(
                name: "Rates");
        }
    }
}
