// <auto-generated />
using CryptoCurrencyExchange.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoCurrencyExchange.Data.Migrations
{
    [DbContext(typeof(CurrencyExchangeRatesDbContext))]
    [Migration("20220825125516_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CryptoCurrencyExchange.Data.Models.Entities.ExchangeRates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatesId");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("CryptoCurrencyExchange.Data.Models.Entities.Rates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AAVE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AED")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AERGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AGLD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIOZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALCX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALEPH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALICE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AMD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AMP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANKR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AOA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ASM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUCTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AXS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AZN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BADGER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BAND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BBD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BICO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOBA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTRST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BWP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BYN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BYR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BZD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C98")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CELR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CGLD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COTI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COVAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTSI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CZK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DASH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DJF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DKK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DREP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DYP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DZD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ELA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETH2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FARM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIDA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FJD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLOW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FORT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FORTH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GALA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GBP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GBX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GGP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GHS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GMD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GNF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GODS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GTQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GYD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GYEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIGH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HNL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HUF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDEX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INDEX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IOTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IQD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JASMY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JPY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JUP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KEEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KGS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KHR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KWD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KYD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KZT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LBP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LCX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LKR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOKA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LQTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LRD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LTL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LYD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MASK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MATIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEDIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("METIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MGA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MKD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MKR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MLN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MTL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MXN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MYR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MZN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NEST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NKN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NZD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OMG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OMR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PKR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POLS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POLY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POWR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUICK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RARE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RARI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPV2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RGT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RWF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SBD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHPING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPELL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STORJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUSHI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SVC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWFTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYLO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SZL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TJS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRIBE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TTD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TZS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UGX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNFI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USDC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UYU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UZS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VEF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VGX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VUV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAMPL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WBTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WCFG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WLUNA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XTS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XTZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XYO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YFI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YFII")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZEC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZMW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZRX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZWD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZWL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_1INCH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rates", (string)null);
                });

            modelBuilder.Entity("CryptoCurrencyExchange.Data.Models.Entities.ExchangeRates", b =>
                {
                    b.HasOne("CryptoCurrencyExchange.Data.Models.Entities.Rates", "Rates")
                        .WithMany()
                        .HasForeignKey("RatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
